- name: create postgresql data directory
  file: path="{{ pg_data_dir }}" state=directory

- name: Install MariaDB container
  docker:
    name: pgsql
    docker_api_version: 1.18
    image: "{{pg_image}}"
    state: started
    env: 
      POSTGRES_PASSWORD: "{{postgres_password}}"
    volumes:
      - "{{ pg_data_dir }}::/var/lib/postgresql/data"