- name: Install Piwik
  docker:
    name: piwik
    docker_api_version: 1.18
    image: "{{piwik_image}}"
    state: started
    links:
      - "piwikdb:db"
    ports:
      - "{{ piwik_port }}:80"

- name: deploy PIWIK configuration
  template: src=piwik.conf.j2 dest=/etc/nginx/conf.d/piwik.conf owner=root group=root mode=0644
  notify:
    - restart nginx